{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8seggjs.serviceAccountName" . }}
  labels:
{{ include "k8seggjs.labels" . | nindent 4 }}
{{- end -}}
