apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8seggjs.fullname" . }}
  labels:
    {{- include "k8seggjs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8seggjs.selectorLabels" . | nindent 4 }}
